# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20171226_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateField(blank=True, null=True),
        ),
    ]
